
# -*- coding: utf-8 -*-

"""
Feature extraction using ResNet-50 pretrained on ImageNet.

The script:
1. Loads the development and test splits generated by Data_Split_lists.py.
2. Loads ResNet-50 with ImageNet pretrained weights.
3. Removes the classification head and applies Global Average Pooling.
4. Extracts a 2048-dimensional feature vector for each cell image.
5. Preserves the original metadata: filepath, label, and group_id.
6. Saves the extracted features to data/features/.

The original five-class labels are preserved at this stage.
Binary relabeling (Normal / Abnormal) will be performed later
during the classification stage.
"""

import os

import numpy as np
import pandas as pd
from tqdm import tqdm
import tensorflow as tf

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D


# ============================================================
# Configuration
# ============================================================

IMG_SIZE = (224, 224)
BATCH_SIZE = 32


# ============================================================
# Project paths
# ============================================================

# Project root:
# project-04-ai-computer-vision-mlops/
project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

splits_dir = os.path.join(project_dir, "data", "splits")
features_dir = os.path.join(project_dir, "data", "features")

os.makedirs(features_dir, exist_ok=True)

dev_path = os.path.join(splits_dir, "dev_data.csv")
test_path = os.path.join(splits_dir, "test_data.csv")

dev_output_path = os.path.join(
    features_dir,
    "dev_features_resnet50.csv"
)

test_output_path = os.path.join(
    features_dir,
    "test_features_resnet50.csv"
)


# ============================================================
# Load dataset splits
# ============================================================

print("===================================")
print("LOADING DATA SPLITS")
print("===================================")

dev_df = pd.read_csv(dev_path)
test_df = pd.read_csv(test_path)

print(f"Development samples: {len(dev_df)}")
print(f"Test samples: {len(test_df)}")


# ============================================================
# Build ResNet-50 feature extractor
# ============================================================

print("\n===================================")
print("BUILDING RESNET-50 FEATURE EXTRACTOR")
print("===================================")

base_model = ResNet50(
    weights="imagenet",
    include_top=False,
    input_shape=(224, 224, 3)
)

# Freeze the pretrained network.
base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)

feature_extractor = Model(
    inputs=base_model.input,
    outputs=x
)

print("ResNet-50 loaded successfully.")
print("Feature vector dimension: 2048")


# ============================================================
# Feature extraction function
# ============================================================

def extract_features(df):
    """
    Extract ResNet-50 features from all images in a dataframe.

    The original metadata is preserved:
        - filepath
        - label
        - group_id

    Returns:
        pandas.DataFrame containing metadata and 2048 features.
    """

    features = []
    filepaths = []
    labels = []
    groups = []

    for _, row in tqdm(
        df.iterrows(),
        total=len(df),
        desc="Extracting features"
    ):

        img_path = row["filepath"]
        label = row["label"]
        group_id = row["group_id"]

        # Load image
        img = image.load_img(
            img_path,
            target_size=IMG_SIZE
        )

        # Convert image to NumPy array
        img_array = image.img_to_array(img)

        # Add batch dimension
        img_array = np.expand_dims(
            img_array,
            axis=0
        )

        # ResNet-50 preprocessing
        img_array = preprocess_input(img_array)

        # Extract features
        feature = feature_extractor.predict(
            img_array,
            verbose=0
        )

        # Store results
        features.append(feature.flatten())
        filepaths.append(img_path)
        labels.append(label)
        groups.append(group_id)

    # Convert feature list to NumPy array
    features = np.array(features)

    # Create dataframe
    feature_df = pd.DataFrame(
        features,
        columns=[
            f"feature_{i:04d}"
            for i in range(features.shape[1])
        ]
    )

    # Add metadata
    feature_df.insert(
        0,
        "filepath",
        filepaths
    )

    feature_df.insert(
        1,
        "label",
        labels
    )

    feature_df.insert(
        2,
        "group_id",
        groups
    )

    return feature_df


# ============================================================
# Extract Development features
# ============================================================

print("\n===================================")
print("EXTRACTING DEVELOPMENT FEATURES")
print("===================================")

dev_features = extract_features(dev_df)

dev_features.to_csv(
    dev_output_path,
    index=False
)

print(f"Development features saved to:")
print(dev_output_path)

print(f"Shape: {dev_features.shape}")


# ============================================================
# Extract Test features
# ============================================================

print("\n===================================")
print("EXTRACTING TEST FEATURES")
print("===================================")

test_features = extract_features(test_df)

test_features.to_csv(
    test_output_path,
    index=False
)

print(f"Test features saved to:")
print(test_output_path)

print(f"Shape: {test_features.shape}")


# ============================================================
# Final summary
# ============================================================

print("\n===================================")
print("FEATURE EXTRACTION COMPLETED")
print("===================================")

print(f"Development features: {dev_features.shape}")
print(f"Test features: {test_features.shape}")

print("\nExpected feature dimension: 2048")
print("Original five-class labels preserved.")
print("No binary relabeling performed at this stage.")

